---
- name: Apache server install
  hosts: node1.canary.local
  become: true
  tasks: 
  - name: latest Apache version installed
    ansible.builtin.package:
      name: httpd
      state: latest 

  - name: latest Apache version installed
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started 
